name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      placeholder: Why is this useful?
